In [1]:
# standard libraries
import pandas as pd
import numpy as np
import re
import os
from IPython.display import Image
import sklearn
import time
import matplotlib.pyplot as plt
import csv

from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split

from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
# csv file name
filename = "log2.csv"

In [3]:

# initializing the titles and rows list
fields = []
rows = []

# reading csv file
with open(filename, 'r') as csvfile:
	# creating a csv reader object
	csvreader = csv.reader(csvfile)
	
	# extracting field names through first row
	fields = next(csvreader)

	# extracting each data row one by one
	for row in csvreader:
		rows.append(row)

	# get total number of rows
	print("Total no. of rows: %d"%(csvreader.line_num))

# printing the field names
print('Field names are:' + ', '.join(field for field in fields))




Total no. of rows: 65533
Field names are:Source Port, Destination Port, NAT Source Port, NAT Destination Port, Action, Bytes, Bytes Sent, Bytes Received, Packets, Elapsed Time (sec), pkts_sent, pkts_received


In [4]:
# convert data set into dataframe
df = pd.read_csv(r"log2.csv")

In [5]:
# assign dependent and independent variables
X = df[['Source Port', 'Destination Port', 'NAT Source Port', 'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received', 'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received']]

In [6]:
y = df['Action']

In [7]:
features = ['X','y']

In [8]:
# data pre-processing
X = preprocessing.StandardScaler().fit(X).transform(X)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)


In [27]:
model = svm.SVC(kernel='poly', degree=2)
model.fit(X_train, y_train)

SVC(degree=2, kernel='poly')

In [28]:
y_pred = svclassifier.predict(X_test)

NameError: name 'svclassifier' is not defined

In [ ]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [ ]:
from sklearn.metrics import accuracy_score
predictions_poly = model.predict(X_test)
accuracy_poly = accuracy_score(y_test, predictions_poly)
print("2nd degree polynomial Kernel\nAccuracy (normalized): " + str(accuracy_poly))

In [ ]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

In [ ]:
Poly_y_pred = svclassifier.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
Gaussian

In [ ]:
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

In [ ]:
Gy_pred = svclassifier.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, Gy_pred))
print(classification_report(y_test, y_pred))

In [9]:
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls


In [10]:
area=df['Action'].value_counts()
labels=(np.array(area.index))
value=(np.array((area/area.sum())*100))
trace=go.Pie(labels=labels,values=value)
layout=go.Layout(title='Action')
data=[trace]
fig=go.Figure(data=data,layout=layout)
py.iplot(fig,filename='Action')

In [11]:
area=df['Elapsed Time (sec)'].value_counts()
labels=(np.array(area.index))
value=(np.array((area/area.sum())*100))
trace=go.Pie(labels=labels,values=value)
layout=go.Layout(title='Elapsed Time (sec)')
data=[trace]
fig=go.Figure(data=data,layout=layout)
py.iplot(fig,filename='Elapsed Time (sec)')

In [15]:
df['Source Port'].value_counts()

58638    840
27005    513
443      273
57470    222
49418    210
        ... 
19302      1
58227      1
47992      1
39804      1
6141       1
Name: Source Port, Length: 22724, dtype: int64

In [16]:
bins = [1023,49151,65535]

In [17]:
df['Source Port'].value_counts(bins=bins, sort=False) 

(1022.999, 49151.0]    15586
(49151.0, 65535.0]     49361
Name: Source Port, dtype: int64

From 0 to 1023 – well known ports assigned to common protocols and services.
From 1024 to 49151 – registered ports assigned by ICANN to a specific service.
From 49152 to 65 535 – dynamic (private, high) ports range from 49,152 to 65,535.